### ISSUE TITLE
help my metamask trust wallet has been hacked, showing reader error” in the big 2024

### ISSUE THREAD

**Issue by Tim79000** [twitter/the-algorithm#1970] opened 2024-01-27 08:47 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by MadKamel** [comment] 2024-01-27 08:48
shocking and appalling. how could musk allow such a thing to happen?? this is why advertisers left

**Comment by AdamFrack** [comment] 2024-01-27 11:42
duplicate of issue #1970

**Comment by kxrn0** [comment] 2024-02-03 18:49
you deserve it

**Closed** 2024-03-21 20:35 UTC

**Comment by dashboarde** [comment] 2024-06-15 13:07
I got same issue earlier but I was referred to support team (REDACTED) they got it fixed earlier, reach out them they has a fix for this
