### ISSUE TITLE
‎  

### ISSUE THREAD

**Issue by llunariis** [twitter/the-algorithm#2007] opened 2024-03-01 15:18 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Exponential-Workload** [comment] 2024-03-01 17:47
Duplicate of #1961

**Comment by llunariis** [comment] 2024-03-02 00:35
> Duplicate of #69

ah shit my bad but there hasn't been any activity on it for awhile, does this still count as a dupe though

**Comment by Exponential-Workload** [comment] 2024-03-02 04:29
> > Duplicate of #69
> 
> ah shit my bad but there hasn't been any activity on it for awhile, does this still count as a dupe though

given necrobumping is allowed i think it does; simply bump [#69](https://github.com/twitter/the-algorithm/issues/69) and see if anyone's interested in a new issue for it

**Comment by llunariis** [comment] 2024-03-02 16:46
> > > Duplicate of #69
> > 
> > 
> > ah shit my bad but there hasn't been any activity on it for awhile, does this still count as a dupe though
> 
> given necrobumping is allowed i think it does; simply bump [#69](https://github.com/twitter/the-algorithm/issues/69) and see if anyone's interested in a new issue for it

ok, tysm!

**Closed as completed** 2024-03-21 20:38 UTC
